baseURL: "https://nadershamma.dev/"
languageCode: "en-gb"
title: "Nader Al-Shamma"
theme: "hello-world"
pygmentsCodeFences: true
permalinks:
  blog: /blog/:year/:title/
  talks: /talks/:year/:title/
params:
  author: "Nader Al-Shamma"
  description: "Nader Al-Shamma"
  og_image: "IMG_20160906_004545.jpg"
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true