baseURL: "https://nadershamma.dev/"
languageCode: "en-gb"
title: "Nader Al-Shamma"
theme: "hello-world"
permalinks:
  blog: /:year/:month/:title/
params:
  author: "Nader Al-Shamma"
  description: "Nader Al-Shamma"
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true